### ISSUE TITLE
Tornado 5.0 broke package

### ISSUE THREAD

**Issue by walliski** [Shizmob/pydle#71]
Tornado 5.0 was released three days ago and broke this package.
```
AttributeError: module 'tornado.concurrent' has no attribute 'TracebackFuture'
```

As a workaround add tornado==4.5.3 in the top of your own requirements.txt before installing pydle.

For pydle's part, you'd need to set dependencies to less than 5.0.0, or a specific version.

**Comment by Shizmob** [comment]
Thanks for reporting, fixed with a lower dependency for now. The `asyncio` branch is the future for pydle, so I don't think I'll be spending much work on making it work with Tornado 5.0+.
